// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdpqteIBuKLPhxbYxraT5LDF7EEz4cwu8',
    appId: '1:719306020643:web:95e0d4dc02f202ac83de96',
    messagingSenderId: '719306020643',
    projectId: 'test-1-5a2c7',
    authDomain: 'test-1-5a2c7.firebaseapp.com',
    storageBucket: 'test-1-5a2c7.firebasestorage.app',
    measurementId: 'G-XW05M8PGRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlzJPVJfMfPglbvTu8_9cMQgOxAJIvBwQ',
    appId: '1:719306020643:android:34f182ab595cc7cd83de96',
    messagingSenderId: '719306020643',
    projectId: 'test-1-5a2c7',
    storageBucket: 'test-1-5a2c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkkMk9N-DsFfW3Dgdk8PdPFEvlAqiVl6A',
    appId: '1:719306020643:ios:43a8ade513c553cf83de96',
    messagingSenderId: '719306020643',
    projectId: 'test-1-5a2c7',
    storageBucket: 'test-1-5a2c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkkMk9N-DsFfW3Dgdk8PdPFEvlAqiVl6A',
    appId: '1:719306020643:ios:43a8ade513c553cf83de96',
    messagingSenderId: '719306020643',
    projectId: 'test-1-5a2c7',
    storageBucket: 'test-1-5a2c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdpqteIBuKLPhxbYxraT5LDF7EEz4cwu8',
    appId: '1:719306020643:web:f6eae3e8b4ff553583de96',
    messagingSenderId: '719306020643',
    projectId: 'test-1-5a2c7',
    authDomain: 'test-1-5a2c7.firebaseapp.com',
    storageBucket: 'test-1-5a2c7.firebasestorage.app',
    measurementId: 'G-QXHMERYSYM',
  );
}
